# Generated by Django 4.1 on 2024-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "BookID",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("BookName", models.CharField(max_length=100)),
                ("NumberOfCopies", models.TextField()),
            ],
            options={
                "db_table": "books",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "MemberID",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("MemberName", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "members",
                "managed": True,
            },
        ),
    ]
