# Generated by Django 4.1 on 2024-04-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_rename_membername_member_membername"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="BookID",
            new_name="bookid",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="BookName",
            new_name="bookname",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="NumberOfCopies",
            new_name="numberofcopies",
        ),
    ]
