# Generated by Django 4.1 on 2024-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_rename_bookid_book_bookid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circulation",
            fields=[
                (
                    "bookid",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("memberid", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "circulation",
                "managed": True,
            },
        ),
    ]
