# Generated by Django 4.1 on 2024-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_circulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="numberofcopies",
            field=models.IntegerField(),
        ),
    ]
