# Generated by Django 4.1 on 2024-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_book_numberofcopies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "bookid",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("memberid", models.CharField(max_length=100)),
                ("reservation_date", models.DateField()),
            ],
            options={
                "db_table": "reservation",
                "managed": True,
            },
        ),
    ]
